### ISSUE TITLE
MC 1.19.x Update support

### ISSUE THREAD

**Issue by Julienraptor01** [kaylendog/rebrand#1]
Could you update your mod to 1.19.2 pls ?
It's been so useful thank you ❤️

**Comment by kaylendog** [comment]
Sure! I wasn't expecting this mod to get any attention at all, so apologies for not updating it sooner. I'll look at this tonight! 😊

**Comment by Julienraptor01** [comment]
Currently it work on 1.19.2 with a simple [dependancy override](https://fabricmc.net/wiki/tutorial:dependency_overrides) but true version support would be great and easier

**Comment by kaylendog** [comment]
Added support in #2! Available on CurseForge once it gets verified.
