### ISSUE TITLE
Can't connect to servers

### ISSUE THREAD

**Issue by TheFruxz** [kaylendog/rebrand#13]
With rebrand-1.1.0 installed on fabric 1.20.1, I can't connect to multiplayer servers anymore. Not even the listing on the server list goes beyond pinging...

**Comment by Finoway** [comment]
Hello,

I found it too. Here are the logs for the developer or anyone who wants to fix the problem ^^

[logs-rebrand-cant-connect.log](https://github.com/kaylendog/rebrand/files/12089829/logs-rebrand-cant-connect.log)

**Comment by Finoway** [comment]
> With rebrand-1.1.0 installed on fabric 1.20.1, I can't connect to multiplayer servers anymore. Not even the listing on the server list goes beyond pinging...

Hello, as a temporary solution I use for the moment. You should take the version 1.0.3 for Minecraft 1.19.4 open the .jar and modify in the file "fabric.mod.json" and change the version of minecraft in dependence of "minecraft": "1.19.4" to the "minecraft": "1.20.1". I downloaded it on modrinth and I have no problem for the moment.

**Comment by kaylendog** [comment]
Are you trying to connect to modded servers?

**Comment by kaylendog** [comment]
> Hello,
> 
> I found it too. Here are the logs for the developer or anyone who wants to fix the problem ^^
> 
> [logs-rebrand-cant-connect.log](https://github.com/kaylendog/rebrand/files/12089829/logs-rebrand-cant-connect.log)

This is odd. Will have a look.

> > With rebrand-1.1.0 installed on fabric 1.20.1, I can't connect to multiplayer servers anymore. Not even the listing on the server list goes beyond pinging...
> 
> Hello, as a temporary solution I use for the moment. You should take the version 1.0.3 for Minecraft 1.19.4 open the .jar and modify in the file "fabric.mod.json" and change the version of minecraft in dependence of "minecraft": "1.19.4" to the "minecraft": "1.20.1". I downloaded it on modrinth and I have no problem for the moment.

This will work as a temporary fix while I investigate.

**Comment by kaylendog** [comment]
Should be fixed in v1.1.1
