### ISSUE TITLE
Possibility of inclusion in LifeMC Studios

### ISSUE THREAD

**Issue by Nukecraft5419** [kaylendog/rebrand#9]
Hi, we at LifeMC Studios were looking for a mod similar to this one, we wanted to know when 1.20.1 will be released we have 3 versions of the modpack 1.18.2, 1.19.4, 1.20.1 and we also wanted to know what kind of data it modifies like in the Debug Menu the one you open with F3

**Comment by kaylendog** [comment]
Go ahead! I meant to relicense the repository as dual MIT-Apache so you wouldn't need explicit permission from me, but I haven't had the time.

All this mod does currently modifies the client's "brand" - this is sent to servers on connection and can be used to spot modded clients. I made the mod primarily to avoid detection when using my performance mods on a vanilla server with a strict vanilla policy. 

The brand can be found on the F3 screen next to the game version - see below:
![image](https://github.com/kaylendog/rebrand/assets/12949077/09dfc9f4-df3a-4356-8964-7938086b7d17)

**Comment by Nukecraft5419** [comment]
So it changes both that and the server itself because on the server side you can detect who uses Vanilla who uses Fabric and who uses Clients like Lunar, Badlion and so on so this makes the modpacks appear as if they were clients like if you put the name LifeMC the cool one will appear yes for 1.20.1 instead I saw that someone made a PR I hope this mod will be supported since after added to the modpack then afterwards you will be mentioned both in the wiki and on the modrinth page and in the list of each version where your mod is present

**Comment by Nukecraft5419** [comment]
I also noticed in the tests that after vanilla it says Fabric by chance is there any way to edit that whole part, then strangely if I put it in 1.18.2 it crashes and I have to deactivate LambDynamicLights

**Comment by Nukecraft5419** [comment]
In the end, your mod was added, and we also put a constraint only in 1.20.1 to run the mod in that version will be removed when a 1.20.1 version comes out

**Comment by kaylendog** [comment]
> 



> I also noticed in the tests that after vanilla it says Fabric by chance is there any way to edit that whole part, then strangely if I put it in 1.18.2 it crashes and I have to deactivate LambDynamicLights

That's probably possible, but I'll need to figure out which part of the Minecraft client edits that content. I'll investigate for you.

**Comment by kaylendog** [comment]
> In the end, your mod was added, and we also put a constraint only in 1.20.1 to run the mod in that version will be removed when a 1.20.1 version comes out

I'm going to get the 1.20.1 release out with ghosting once I'm back from Rome.

**Comment by Nukecraft5419** [comment]
Excuse me, are you Italian?

**Comment by kaylendog** [comment]
> Excuse me, are you Italian?

UKian! Closing since you seem happy.
